/* KRIM API FOUNDATION */

const KRIM_API = {

    async request(path, options = {}) {

            const session = await KRIM_AUTH.getSession();

                    const headers = {
                                "apikey": KRIM_CONFIG.supabase.publishableKey,
                                            "Content-Type": "application/json"
                                                    };

                                                            if (session && session.access_token) {
                                                                        headers["Authorization"] =
                                                                                        "Bearer " + session.access_token;
                                                                                                }

                                                                                                        const response = await fetch(
                                                                                                                    KRIM_CONFIG.supabase.url + path,
                                                                                                                                {
                                                                                                                                                method: options.method || "GET",
                                                                                                                                                                headers: headers,
                                                                                                                                                                                body: options.body
                                                                                                                                                                                                    ? JSON.stringify(options.body)
                                                                                                                                                                                                                        : undefined
                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                            );

                                                                                                                                                                                                                                                    if (!response.ok) {
                                                                                                                                                                                                                                                                throw new Error(
                                                                                                                                                                                                                                                                                "KRIM API request failed: " +
                                                                                                                                                                                                                                                                                                response.status
                                                                                                                                                                                                                                                                                                            );
                                                                                                                                                                                                                                                                                                                    }

                                                                                                                                                                                                                                                                                                                            return await response.json();
                                                                                                                                                                                                                                                                                                                                },


                                                                                                                                                                                                                                                                                                                                    async get(path) {
                                                                                                                                                                                                                                                                                                                                            return await this.request(path);
                                                                                                                                                                                                                                                                                                                                                },


                                                                                                                                                                                                                                                                                                                                                    async post(path, data) {
                                                                                                                                                                                                                                                                                                                                                            return await this.request(path, {
                                                                                                                                                                                                                                                                                                                                                                        method: "POST",
                                                                                                                                                                                                                                                                                                                                                                                    body: data
                                                                                                                                                                                                                                                                                                                                                                                            });
                                                                                                                                                                                                                                                                                                                                                                                                },


                                                                                                                                                                                                                                                                                                                                                                                                    async patch(path, data) {
                                                                                                                                                                                                                                                                                                                                                                                                            return await this.request(path, {
                                                                                                                                                                                                                                                                                                                                                                                                                        method: "PATCH",
                                                                                                                                                                                                                                                                                                                                                                                                                                    body: data
                                                                                                                                                                                                                                                                                                                                                                                                                                            });
                                                                                                                                                                                                                                                                                                                                                                                                                                                },


                                                                                                                                                                                                                                                                                                                                                                                                                                                    async delete(path) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                            return await this.request(path, {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        method: "DELETE"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    };